apiVersion: v1
kind: Service
metadata:
  name: local-fs-service
  namespace: system
  labels:
    control-plane: local-fs
    controller-tools.k8s.io: "1.0"
    koalja-service: FileSystem
spec:
  selector:
    control-plane: local-fs
    controller-tools.k8s.io: "1.0"
  ports:
  - port: 7212
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: local-fs
  namespace: system
  labels:
    control-plane: local-fs
    controller-tools.k8s.io: "1.0"
spec:
  selector:
    matchLabels:
      control-plane: local-fs
      controller-tools.k8s.io: "1.0"
  serviceName: local-fs-service
  template:
    metadata:
      labels:
        control-plane: local-fs
        controller-tools.k8s.io: "1.0"
    spec:
      containers:
      - command:
        - /apps/services
        - filesystem
        - --filesystem=local
        image: koalja-services:latest
        name: fs-service
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
        - name: KOALJA_API_PORT
          value: "7212"
        - name: KOALJA_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KOALJA_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      terminationGracePeriodSeconds: 10
