// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent_api.proto

package pipeline

import (
	fmt "fmt"
	event "github.com/AljabrIO/koalja-operator/pkg/event"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterLinkRequest struct {
	// Name of the link
	LinkName string `protobuf:"bytes,1,opt,name=LinkName,proto3" json:"LinkName,omitempty"`
	// URI of the link
	URI                  string   `protobuf:"bytes,2,opt,name=URI,proto3" json:"URI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterLinkRequest) Reset()         { *m = RegisterLinkRequest{} }
func (m *RegisterLinkRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterLinkRequest) ProtoMessage()    {}
func (*RegisterLinkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_011b677ced0569e6, []int{0}
}

func (m *RegisterLinkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterLinkRequest.Unmarshal(m, b)
}
func (m *RegisterLinkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterLinkRequest.Marshal(b, m, deterministic)
}
func (m *RegisterLinkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterLinkRequest.Merge(m, src)
}
func (m *RegisterLinkRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterLinkRequest.Size(m)
}
func (m *RegisterLinkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterLinkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterLinkRequest proto.InternalMessageInfo

func (m *RegisterLinkRequest) GetLinkName() string {
	if m != nil {
		return m.LinkName
	}
	return ""
}

func (m *RegisterLinkRequest) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

type RegisterTaskRequest struct {
	// Name of the task
	TaskName string `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	// URI of the task
	URI                  string   `protobuf:"bytes,2,opt,name=URI,proto3" json:"URI,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterTaskRequest) Reset()         { *m = RegisterTaskRequest{} }
func (m *RegisterTaskRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterTaskRequest) ProtoMessage()    {}
func (*RegisterTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_011b677ced0569e6, []int{1}
}

func (m *RegisterTaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTaskRequest.Unmarshal(m, b)
}
func (m *RegisterTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTaskRequest.Marshal(b, m, deterministic)
}
func (m *RegisterTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTaskRequest.Merge(m, src)
}
func (m *RegisterTaskRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterTaskRequest.Size(m)
}
func (m *RegisterTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTaskRequest proto.InternalMessageInfo

func (m *RegisterTaskRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *RegisterTaskRequest) GetURI() string {
	if m != nil {
		return m.URI
	}
	return ""
}

type OutputEventsRequest struct {
	// EventIDs is a list of event IDs.
	// The response will include only events that are (indirectly) related
	// to any of these event IDs.
	EventIDs []string `protobuf:"bytes,1,rep,name=EventIDs,proto3" json:"EventIDs,omitempty"`
	// TaskNames is a list of names of tasks.
	// The response will include only events that are created by one of these tasks.
	TaskNames []string `protobuf:"bytes,2,rep,name=TaskNames,proto3" json:"TaskNames,omitempty"`
	// If set, only events created after this timestamp are returned.
	CreatedAfter *timestamp.Timestamp `protobuf:"bytes,3,opt,name=CreatedAfter,proto3" json:"CreatedAfter,omitempty"`
	// If set, only events created before this timestamp are returned.
	CreatedBefore        *timestamp.Timestamp `protobuf:"bytes,4,opt,name=CreatedBefore,proto3" json:"CreatedBefore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OutputEventsRequest) Reset()         { *m = OutputEventsRequest{} }
func (m *OutputEventsRequest) String() string { return proto.CompactTextString(m) }
func (*OutputEventsRequest) ProtoMessage()    {}
func (*OutputEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_011b677ced0569e6, []int{2}
}

func (m *OutputEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputEventsRequest.Unmarshal(m, b)
}
func (m *OutputEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputEventsRequest.Marshal(b, m, deterministic)
}
func (m *OutputEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputEventsRequest.Merge(m, src)
}
func (m *OutputEventsRequest) XXX_Size() int {
	return xxx_messageInfo_OutputEventsRequest.Size(m)
}
func (m *OutputEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OutputEventsRequest proto.InternalMessageInfo

func (m *OutputEventsRequest) GetEventIDs() []string {
	if m != nil {
		return m.EventIDs
	}
	return nil
}

func (m *OutputEventsRequest) GetTaskNames() []string {
	if m != nil {
		return m.TaskNames
	}
	return nil
}

func (m *OutputEventsRequest) GetCreatedAfter() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAfter
	}
	return nil
}

func (m *OutputEventsRequest) GetCreatedBefore() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedBefore
	}
	return nil
}

type OutputEvents struct {
	// The selected events
	Events               []*event.Event `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *OutputEvents) Reset()         { *m = OutputEvents{} }
func (m *OutputEvents) String() string { return proto.CompactTextString(m) }
func (*OutputEvents) ProtoMessage()    {}
func (*OutputEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_011b677ced0569e6, []int{3}
}

func (m *OutputEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputEvents.Unmarshal(m, b)
}
func (m *OutputEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputEvents.Marshal(b, m, deterministic)
}
func (m *OutputEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputEvents.Merge(m, src)
}
func (m *OutputEvents) XXX_Size() int {
	return xxx_messageInfo_OutputEvents.Size(m)
}
func (m *OutputEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputEvents.DiscardUnknown(m)
}

var xxx_messageInfo_OutputEvents proto.InternalMessageInfo

func (m *OutputEvents) GetEvents() []*event.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterLinkRequest)(nil), "pipeline.RegisterLinkRequest")
	proto.RegisterType((*RegisterTaskRequest)(nil), "pipeline.RegisterTaskRequest")
	proto.RegisterType((*OutputEventsRequest)(nil), "pipeline.OutputEventsRequest")
	proto.RegisterType((*OutputEvents)(nil), "pipeline.OutputEvents")
}

func init() { proto.RegisterFile("agent_api.proto", fileDescriptor_011b677ced0569e6) }

var fileDescriptor_011b677ced0569e6 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x93, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xc7, 0xd9, 0x44, 0x4a, 0x3b, 0x4d, 0xad, 0x4e, 0x31, 0x2c, 0x4b, 0x84, 0x10, 0xbc, 0x28,
	0x82, 0x3b, 0x98, 0x8a, 0x88, 0x82, 0x98, 0xd6, 0x20, 0x01, 0xb1, 0xb0, 0xd4, 0x1b, 0x6f, 0x64,
	0xa2, 0x27, 0xeb, 0x34, 0xbb, 0x3b, 0xe3, 0xcc, 0xd9, 0x62, 0x6e, 0x7d, 0x05, 0xaf, 0x7d, 0x28,
	0xf1, 0x15, 0x7c, 0x10, 0x99, 0x99, 0x6c, 0x3b, 0xc1, 0x95, 0xdc, 0x2c, 0xf3, 0x3f, 0x67, 0xe6,
	0xb7, 0xe7, 0x93, 0x1c, 0xf2, 0x1c, 0x2a, 0xfc, 0xc8, 0x95, 0x48, 0x95, 0x96, 0x28, 0xe9, 0xae,
	0x12, 0x0a, 0x0a, 0x51, 0x41, 0xf2, 0x22, 0x17, 0xf8, 0xa5, 0x9e, 0xa7, 0x9f, 0x64, 0xc9, 0x72,
	0x59, 0xf0, 0x2a, 0x67, 0xee, 0xca, 0xbc, 0x5e, 0x30, 0x85, 0x2b, 0x05, 0x86, 0xa1, 0x28, 0xc1,
	0x20, 0x2f, 0xd5, 0xcd, 0xc9, 0x63, 0x92, 0x93, 0xed, 0x8f, 0xa1, 0x54, 0xb8, 0xf2, 0xdf, 0xf5,
	0xa3, 0x7b, 0x6a, 0x99, 0x33, 0xb8, 0x82, 0x0a, 0xfd, 0x77, 0x6d, 0x1e, 0xe4, 0x52, 0xe6, 0x05,
	0x30, 0xae, 0x04, 0xe3, 0x55, 0x25, 0x91, 0xa3, 0x90, 0x95, 0xf1, 0xde, 0xd1, 0x19, 0x39, 0xca,
	0x20, 0x17, 0x06, 0x41, 0xbf, 0x15, 0xd5, 0x32, 0x83, 0xaf, 0x35, 0x18, 0xa4, 0x09, 0xd9, 0xb5,
	0xf2, 0x1d, 0x2f, 0x21, 0x8e, 0x86, 0xd1, 0xf1, 0x5e, 0x76, 0xad, 0xe9, 0x1d, 0xd2, 0x7d, 0x9f,
	0xcd, 0xe2, 0x8e, 0x33, 0xdb, 0x63, 0x08, 0xb9, 0xe0, 0x26, 0x84, 0x58, 0x19, 0x42, 0x1a, 0xdd,
	0x02, 0xf9, 0x15, 0x91, 0xa3, 0xf3, 0x1a, 0x55, 0x8d, 0x53, 0x1b, 0xbd, 0x09, 0x28, 0xce, 0x30,
	0x7b, 0x6d, 0xe2, 0x68, 0xd8, 0xb5, 0x94, 0x46, 0xd3, 0x01, 0xd9, 0x6b, 0x88, 0x26, 0xee, 0x38,
	0xe7, 0x8d, 0x81, 0xbe, 0x24, 0xbd, 0x33, 0x0d, 0x1c, 0xe1, 0xf3, 0x64, 0x81, 0xa0, 0xe3, 0xee,
	0x30, 0x3a, 0xde, 0x1f, 0x27, 0xa9, 0x2f, 0x48, 0xda, 0x54, 0x34, 0xbd, 0x68, 0xaa, 0x9f, 0x6d,
	0xdc, 0xa7, 0xaf, 0xc8, 0xc1, 0x5a, 0x9f, 0xc2, 0x42, 0x6a, 0x88, 0x6f, 0x6d, 0x05, 0x6c, 0x3e,
	0x18, 0x3d, 0x21, 0xbd, 0x30, 0x25, 0xfa, 0x80, 0xec, 0xf8, 0x93, 0xcb, 0x64, 0x7f, 0xdc, 0x4b,
	0x7d, 0xa7, 0x9c, 0x31, 0x5b, 0xfb, 0xc6, 0x3f, 0x23, 0x72, 0x30, 0xb1, 0x83, 0xe5, 0x8b, 0xaa,
	0x57, 0x74, 0x4a, 0x7a, 0x61, 0x97, 0xe8, 0xfd, 0xb4, 0x99, 0xb3, 0xb4, 0xa5, 0x7b, 0x49, 0xff,
	0x9f, 0x08, 0xa7, 0x76, 0x4e, 0x42, 0x8c, 0xad, 0x52, 0x1b, 0x26, 0xe8, 0xdf, 0xff, 0x30, 0xe3,
	0x6f, 0xe4, 0xb6, 0xcf, 0xea, 0x3a, 0xbe, 0x05, 0x39, 0x7c, 0x03, 0xb8, 0x91, 0x6a, 0xc0, 0x6e,
	0xe9, 0x6a, 0xd2, 0x6f, 0x77, 0x8f, 0x06, 0xdf, 0x7f, 0xff, 0xf9, 0xd1, 0xe9, 0x8f, 0xee, 0xb2,
	0xab, 0xc7, 0x4c, 0x3a, 0x8f, 0x9f, 0x66, 0xf3, 0x3c, 0x7a, 0x78, 0xfa, 0xec, 0xc3, 0xd3, 0x60,
	0x33, 0x26, 0xc5, 0x25, 0x9f, 0xeb, 0xd9, 0x39, 0x5b, 0x4a, 0x5e, 0x5c, 0xf2, 0x47, 0x52, 0x81,
	0xe6, 0x28, 0x35, 0xb3, 0x8b, 0xe0, 0x36, 0x93, 0x35, 0x3f, 0x99, 0xef, 0xb8, 0x1c, 0x4e, 0xfe,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x51, 0x85, 0x8f, 0xb2, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentRegistryClient is the client API for AgentRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentRegistryClient interface {
	// Register an instance of a link agent
	RegisterLink(ctx context.Context, in *RegisterLinkRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Register an instance of a task agent
	RegisterTask(ctx context.Context, in *RegisterTaskRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type agentRegistryClient struct {
	cc *grpc.ClientConn
}

func NewAgentRegistryClient(cc *grpc.ClientConn) AgentRegistryClient {
	return &agentRegistryClient{cc}
}

func (c *agentRegistryClient) RegisterLink(ctx context.Context, in *RegisterLinkRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pipeline.AgentRegistry/RegisterLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRegistryClient) RegisterTask(ctx context.Context, in *RegisterTaskRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/pipeline.AgentRegistry/RegisterTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRegistryServer is the server API for AgentRegistry service.
type AgentRegistryServer interface {
	// Register an instance of a link agent
	RegisterLink(context.Context, *RegisterLinkRequest) (*empty.Empty, error)
	// Register an instance of a task agent
	RegisterTask(context.Context, *RegisterTaskRequest) (*empty.Empty, error)
}

func RegisterAgentRegistryServer(s *grpc.Server, srv AgentRegistryServer) {
	s.RegisterService(&_AgentRegistry_serviceDesc, srv)
}

func _AgentRegistry_RegisterLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRegistryServer).RegisterLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipeline.AgentRegistry/RegisterLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRegistryServer).RegisterLink(ctx, req.(*RegisterLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRegistry_RegisterTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRegistryServer).RegisterTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipeline.AgentRegistry/RegisterTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRegistryServer).RegisterTask(ctx, req.(*RegisterTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pipeline.AgentRegistry",
	HandlerType: (*AgentRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterLink",
			Handler:    _AgentRegistry_RegisterLink_Handler,
		},
		{
			MethodName: "RegisterTask",
			Handler:    _AgentRegistry_RegisterTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_api.proto",
}

// OutputRegistryClient is the client API for OutputRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OutputRegistryClient interface {
	// GetOutputEvents returns all events (resulting from task outputs that
	// are not connected to inputs of other tasks) that match the given filter.
	GetOutputEvents(ctx context.Context, in *OutputEventsRequest, opts ...grpc.CallOption) (*OutputEvents, error)
}

type outputRegistryClient struct {
	cc *grpc.ClientConn
}

func NewOutputRegistryClient(cc *grpc.ClientConn) OutputRegistryClient {
	return &outputRegistryClient{cc}
}

func (c *outputRegistryClient) GetOutputEvents(ctx context.Context, in *OutputEventsRequest, opts ...grpc.CallOption) (*OutputEvents, error) {
	out := new(OutputEvents)
	err := c.cc.Invoke(ctx, "/pipeline.OutputRegistry/GetOutputEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OutputRegistryServer is the server API for OutputRegistry service.
type OutputRegistryServer interface {
	// GetOutputEvents returns all events (resulting from task outputs that
	// are not connected to inputs of other tasks) that match the given filter.
	GetOutputEvents(context.Context, *OutputEventsRequest) (*OutputEvents, error)
}

func RegisterOutputRegistryServer(s *grpc.Server, srv OutputRegistryServer) {
	s.RegisterService(&_OutputRegistry_serviceDesc, srv)
}

func _OutputRegistry_GetOutputEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OutputEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OutputRegistryServer).GetOutputEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pipeline.OutputRegistry/GetOutputEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OutputRegistryServer).GetOutputEvents(ctx, req.(*OutputEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OutputRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pipeline.OutputRegistry",
	HandlerType: (*OutputRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOutputEvents",
			Handler:    _OutputRegistry_GetOutputEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent_api.proto",
}
