FROM golang:1.11-alpine

RUN apk add -U git protobuf && \
    go get k8s.io/code-generator/cmd/go-to-protobuf && \
    go get github.com/gogo/protobuf/protoc-gen-gogo && \
    go get github.com/gogo/protobuf/protoc-gen-gofast && \
    go get golang.org/x/tools/cmd/goimports && \
    go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway && \
    go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger && \
    go get -u github.com/golang/protobuf/protoc-gen-go
