apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: linksidecars.agents.aljabr.io
spec:
  group: agents.aljabr.io
  names:
    kind: LinkSidecar
    plural: linksidecars
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            container:
              type: object
            format:
              type: string
            protocol:
              type: string
          required:
          - protocol
          - container
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
