apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: taskexecutors.agents.aljabr.io
spec:
  group: agents.aljabr.io
  names:
    kind: TaskExecutor
    plural: taskexecutors
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            container:
              type: object
            routes:
              items:
                properties:
                  enableWebsockets:
                    type: boolean
                  name:
                    type: string
                  port:
                    format: int64
                    type: integer
                  prefixRewrite:
                    type: string
                required:
                - name
                - port
                type: object
              type: array
            type:
              type: string
          required:
          - type
          - container
          type: object
        status:
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
