apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - v1
  resources:
  - serviceaccounts
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - v1
  resources:
  - services
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - koalja.aljabr.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - v1
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - v1
  resources:
  - serviceaccounts
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - update
  - patch
  - delete
- apiGroups:
  - agents.aljabr.io
  resources:
  - pipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.aljabr.io
  resources:
  - eventregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.aljabr.io
  resources:
  - links
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.aljabr.io
  resources:
  - tasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agents.aljabr.io
  resources:
  - taskexecutors
  verbs:
  - get
  - list
  - watch
