apiVersion: koalja.aljabr.io/v1alpha1
kind: Pipeline
metadata:
  name: csv-clean-and-total
  namespace: default
spec:
  tasks:
  - name: fileDropInput
    outputs:
    - name: droppedFile
      typeRef: singleCSVFile
      ready: Auto
    type: FileDrop
  - name: cleanCSV
    inputs:
    - name: csvInputFile
      typeRef: singleCSVFile
    outputs:
    - name: csvOutputFile
      typeRef: singleCSVFile
      ready: Succeeded
    executor:
      image: ewoutp/cleanCSVConverter:latest
      args: ["--input", "{{.inputs.csvInputFile.path }}", "--output", "{{.outputs.csvOutputFile.path}}"]
  - name: totalCSV
    inputs:
    - name: csvInputFile
      typeRef: singleCSVFile
    outputs:
    - name: csvOutputFile
      typeRef: singleCSVFile
      ready: Succeeded
    executor:
      image: ewoutp/summarizeCSVConverter:latest
      args: ["--input", "{{.inputs.csvInputFile.path }}", "--output", "{{.outputs.csvOutputFile.path}}"]
  links:
  - name: csvInput
    sourceRef: fileDropInput/droppedFile
    destinationRef: cleanCSV/csvInputFile
  - name: fromCleanToTotal
    sourceRef: cleanCSV/csvOutputFile
    destinationRef: totalCSV/csvInputFile
  types:
  - name: singleCSVFile
    protocol: File
    format: CSV
