apiVersion: koalja.aljabr.io/v1alpha1
kind: Pipeline
metadata:
  name: linecount-mergeinto
  namespace: default
spec:
  tasks:
  - name: fileDropInput1
    outputs:
    - name: droppedFile
      typeRef: singleTextFile
      ready: Auto
    type: FileDrop
  - name: fileDropInput2
    outputs:
    - name: droppedFile
      typeRef: singleTextFile
      ready: Auto
    type: FileDrop
  - name: removeDuplicates
    inputs:
    - name: inputFile1
      typeRef: singleTextFile
    - name: inputFile2
      typeRef: singleTextFile
      mergeInto: inputFile1
    outputs:
    - name: outputFile
      typeRef: singleTextFile
      ready: Succeeded
    executor:
      image: alpine:latest
      command:
      - /bin/sh 
      - -c 
      - "cat {{.inputs.inputFile1.path }} | uniq > {{.outputs.outputFile.path}}"
  - name: countLines
    inputs:
    - name: inputFile
      typeRef: singleTextFile
    outputs:
    - name: outputFile
      typeRef: singleTextFile
      ready: Succeeded
    executor:
      image: alpine:latest
      command:
      - /bin/sh 
      - -c 
      - "cat {{.inputs.inputFile.path }} | wc -l > {{.outputs.outputFile.path}}"
  links:
  - name: from1ToToUniq
    sourceRef: fileDropInput1/droppedFile
    destinationRef: removeDuplicates/inputFile1
  - name: from2ToToUniq
    sourceRef: fileDropInput2/droppedFile
    destinationRef: removeDuplicates/inputFile2
  - name: fromUniqToCount
    sourceRef: removeDuplicates/outputFile
    destinationRef: countLines/inputFile
  types:
  - name: singleTextFile
    protocol: File
    format: Text
