apiVersion: koalja.aljabr.io/v1alpha1
kind: Pipeline
metadata:
  name: tf-fashion
  namespace: default
spec:
  tasks:
  - name: scriptInput
    outputs:
    - name: droppedFile
      typeRef: scriptFile
      ready: Auto
    type: FileDrop
  - name: learn
    inputs:
    - name: script
      typeRef: scriptFile
    outputs:
    - name: model
      typeRef: modelFile
      ready: Succeeded
    executor:
      image: tensorflow/tensorflow
      command:
      - python
      - "{{.inputs.inputFile.path }}"
      - "{{.outputs.outputFile.path}}"
  - name: imageInput
    outputs:
    - name: droppedFile
      typeRef: imageFile
      ready: Auto
    type: FileDrop
  - name: serve
    launchPolicy: Restart
    inputs:
    - name: model
      typeRef: modelFile
    - name: image
      typeRef: imageFile
    service:
      ports:
      - name: http
        port: 8501
    executor:
      image: tensorflow/serving
      command:
      - tensorflow_model_server
      - --port=8500
      - --rest_api_port=8501
      - --model_name=mymodel
      - --model_base_path={{.inputs.model.path }} 
  - name: predict
    launchPolicy: Custom
    inputs:
    - name: image
      typeRef: imageFile
    outputs:
    - name: prediction
      typeRef: predictionFile
      ready: Auto
      options:
        url: "http://{{.tasks.serve.service.name}}:8501/v1/models/mymodel:predict"
        method: "GET"
        body: "{{readURI(.snapshot.image.uri) }}"
    type: REST
  links:
  - name: scriptInput-learn
    sourceRef: scriptInput/droppedFile
    destinationRef: learn/script
  - name: imageInput-predict
    sourceRef: imageInput/droppedFile
    destinationRef: predict/image
  - name: learn-serve
    sourceRef: learn/model
    destinationRef: serve/model
  types:
  - name: scriptFile
    protocol: File
    format: Text
  - name: imageFile
    protocol: File
    format: Image
  - name: modelFile
    protocol: File
    format: TFModel
  - name: predictionFile
    protocol: File
    format: TFPrediction
