// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: local.proto

package local // import "github.com/AljabrIO/koalja-operator/pkg/fs/service/local"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import fs "github.com/AljabrIO/koalja-operator/pkg/fs"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "k8s.io/apimachinery/pkg/apis/meta/v1"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegisterNodeRequest struct {
	// Name of the Node.
	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	// Address of the Node API.
	NodeAddress          string   `protobuf:"bytes,2,opt,name=NodeAddress,proto3" json:"NodeAddress,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterNodeRequest) Reset()         { *m = RegisterNodeRequest{} }
func (m *RegisterNodeRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterNodeRequest) ProtoMessage()    {}
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_local_ba6610d3e375043a, []int{0}
}
func (m *RegisterNodeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegisterNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegisterNodeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *RegisterNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterNodeRequest.Merge(dst, src)
}
func (m *RegisterNodeRequest) XXX_Size() int {
	return m.Size()
}
func (m *RegisterNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterNodeRequest proto.InternalMessageInfo

func (m *RegisterNodeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterNodeRequest) GetNodeAddress() string {
	if m != nil {
		return m.NodeAddress
	}
	return ""
}

type CreateFileViewRequest struct {
	// The path of the node of the file to create a view for
	LocalPath string `protobuf:"bytes,1,opt,name=LocalPath,proto3" json:"LocalPath,omitempty"`
	// If set, a small preview is returned instead of the full content
	Preview              bool     `protobuf:"varint,2,opt,name=Preview,proto3" json:"Preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateFileViewRequest) Reset()         { *m = CreateFileViewRequest{} }
func (m *CreateFileViewRequest) String() string { return proto.CompactTextString(m) }
func (*CreateFileViewRequest) ProtoMessage()    {}
func (*CreateFileViewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_local_ba6610d3e375043a, []int{1}
}
func (m *CreateFileViewRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateFileViewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateFileViewRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CreateFileViewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateFileViewRequest.Merge(dst, src)
}
func (m *CreateFileViewRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateFileViewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateFileViewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateFileViewRequest proto.InternalMessageInfo

func (m *CreateFileViewRequest) GetLocalPath() string {
	if m != nil {
		return m.LocalPath
	}
	return ""
}

func (m *CreateFileViewRequest) GetPreview() bool {
	if m != nil {
		return m.Preview
	}
	return false
}

func init() {
	proto.RegisterType((*RegisterNodeRequest)(nil), "local.RegisterNodeRequest")
	proto.RegisterType((*CreateFileViewRequest)(nil), "local.CreateFileViewRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeRegistryClient is the client API for NodeRegistry service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeRegistryClient interface {
	// CreateFileView returns a view on the given file identified by the given URI.
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type nodeRegistryClient struct {
	cc *grpc.ClientConn
}

func NewNodeRegistryClient(cc *grpc.ClientConn) NodeRegistryClient {
	return &nodeRegistryClient{cc}
}

func (c *nodeRegistryClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/local.NodeRegistry/RegisterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeRegistryServer is the server API for NodeRegistry service.
type NodeRegistryServer interface {
	// CreateFileView returns a view on the given file identified by the given URI.
	RegisterNode(context.Context, *RegisterNodeRequest) (*empty.Empty, error)
}

func RegisterNodeRegistryServer(s *grpc.Server, srv NodeRegistryServer) {
	s.RegisterService(&_NodeRegistry_serviceDesc, srv)
}

func _NodeRegistry_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeRegistryServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/local.NodeRegistry/RegisterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeRegistryServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeRegistry_serviceDesc = grpc.ServiceDesc{
	ServiceName: "local.NodeRegistry",
	HandlerType: (*NodeRegistryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _NodeRegistry_RegisterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "local.proto",
}

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	// CreateFileView returns a view on the given file identified by the given URI.
	CreateFileView(ctx context.Context, in *CreateFileViewRequest, opts ...grpc.CallOption) (*fs.CreateFileViewResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) CreateFileView(ctx context.Context, in *CreateFileViewRequest, opts ...grpc.CallOption) (*fs.CreateFileViewResponse, error) {
	out := new(fs.CreateFileViewResponse)
	err := c.cc.Invoke(ctx, "/local.Node/CreateFileView", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	// CreateFileView returns a view on the given file identified by the given URI.
	CreateFileView(context.Context, *CreateFileViewRequest) (*fs.CreateFileViewResponse, error)
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_CreateFileView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).CreateFileView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/local.Node/CreateFileView",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).CreateFileView(ctx, req.(*CreateFileViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "local.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateFileView",
			Handler:    _Node_CreateFileView_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "local.proto",
}

func (m *RegisterNodeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegisterNodeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLocal(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.NodeAddress) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintLocal(dAtA, i, uint64(len(m.NodeAddress)))
		i += copy(dAtA[i:], m.NodeAddress)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *CreateFileViewRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateFileViewRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.LocalPath) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintLocal(dAtA, i, uint64(len(m.LocalPath)))
		i += copy(dAtA[i:], m.LocalPath)
	}
	if m.Preview {
		dAtA[i] = 0x10
		i++
		if m.Preview {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintLocal(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *RegisterNodeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovLocal(uint64(l))
	}
	l = len(m.NodeAddress)
	if l > 0 {
		n += 1 + l + sovLocal(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CreateFileViewRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.LocalPath)
	if l > 0 {
		n += 1 + l + sovLocal(uint64(l))
	}
	if m.Preview {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovLocal(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozLocal(x uint64) (n int) {
	return sovLocal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegisterNodeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegisterNodeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegisterNodeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipLocal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLocal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateFileViewRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowLocal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateFileViewRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateFileViewRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LocalPath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthLocal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LocalPath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Preview", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowLocal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Preview = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipLocal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthLocal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipLocal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowLocal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowLocal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthLocal
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowLocal
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipLocal(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthLocal = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowLocal   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("local.proto", fileDescriptor_local_ba6610d3e375043a) }

var fileDescriptor_local_ba6610d3e375043a = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x6f, 0x1a, 0x31,
	0x10, 0xed, 0x56, 0xf4, 0x03, 0x83, 0x7a, 0x70, 0xd5, 0x0a, 0xad, 0xd0, 0x0a, 0x71, 0xea, 0xa5,
	0xb6, 0x0a, 0x3d, 0x70, 0x85, 0xaa, 0x95, 0x4a, 0x22, 0x40, 0x7b, 0xc8, 0x21, 0x37, 0xef, 0xee,
	0xac, 0x31, 0xec, 0xae, 0x1d, 0xdb, 0x80, 0xf6, 0x9f, 0xe4, 0x27, 0xe5, 0x98, 0x9f, 0x10, 0x91,
	0x3f, 0x12, 0xad, 0x17, 0x14, 0xa2, 0x70, 0xc9, 0xc5, 0xf2, 0xcc, 0xf3, 0x7b, 0xf3, 0xe6, 0x19,
	0xb5, 0x32, 0x19, 0xb3, 0x8c, 0x28, 0x2d, 0xad, 0xc4, 0x1f, 0x5c, 0xe1, 0xff, 0x5e, 0x8f, 0x0c,
	0x11, 0x92, 0x32, 0x25, 0x72, 0x16, 0x2f, 0x45, 0x01, 0xba, 0xa4, 0x6a, 0xcd, 0xab, 0x86, 0xa1,
	0x39, 0x58, 0x46, 0xb7, 0xbf, 0x28, 0x87, 0x02, 0x34, 0xb3, 0x90, 0xd4, 0x64, 0x7f, 0xc8, 0x85,
	0x5d, 0x6e, 0x22, 0x12, 0xcb, 0x9c, 0x72, 0x99, 0xb1, 0x82, 0x53, 0x07, 0x44, 0x9b, 0x94, 0x2a,
	0x5b, 0x2a, 0x30, 0x14, 0x72, 0x65, 0xcb, 0xfa, 0x3c, 0x43, 0x1a, 0x67, 0x2b, 0x16, 0xe9, 0xff,
	0x73, 0xba, 0x96, 0x2c, 0x5b, 0xb1, 0x9f, 0x52, 0x55, 0xfa, 0x52, 0xbb, 0xd1, 0xa9, 0xa1, 0xa9,
	0xa9, 0x49, 0xfd, 0x0b, 0xf4, 0x35, 0x04, 0x2e, 0x8c, 0x05, 0x3d, 0x93, 0x09, 0x84, 0x70, 0xb3,
	0x01, 0x63, 0x31, 0x46, 0x8d, 0x19, 0xcb, 0xa1, 0xe3, 0xf5, 0xbc, 0x1f, 0xcd, 0xd0, 0xdd, 0x71,
	0x0f, 0xb5, 0xaa, 0x27, 0xe3, 0x24, 0xd1, 0x60, 0x4c, 0xe7, 0xbd, 0x83, 0x4e, 0x5b, 0xfd, 0x39,
	0xfa, 0xf6, 0x47, 0x03, 0xb3, 0xf0, 0x4f, 0x64, 0x70, 0x25, 0x60, 0x77, 0x94, 0xeb, 0xa2, 0xe6,
	0x65, 0x15, 0xc7, 0x82, 0xd9, 0xe5, 0x41, 0xf3, 0xb9, 0x81, 0x3b, 0xe8, 0xd3, 0x42, 0xc3, 0x56,
	0xc0, 0xce, 0x89, 0x7e, 0x0e, 0x8f, 0xe5, 0x20, 0x44, 0xed, 0xda, 0x55, 0xe5, 0x50, 0x97, 0x78,
	0x82, 0xda, 0xa7, 0x6e, 0xb1, 0x4f, 0xea, 0xc8, 0xcf, 0xac, 0xe0, 0x7f, 0x27, 0x5c, 0x4a, 0x9e,
	0x01, 0x39, 0x26, 0x47, 0xfe, 0x56, 0x61, 0x0d, 0x42, 0xd4, 0x70, 0xdc, 0x29, 0xfa, 0xf2, 0xd2,
	0x2c, 0xee, 0x1e, 0xd4, 0xce, 0xee, 0xe0, 0xfb, 0x24, 0x35, 0xaf, 0x20, 0xa3, 0x64, 0x61, 0x60,
	0x32, 0xbd, 0xdb, 0x07, 0xde, 0xfd, 0x3e, 0xf0, 0x1e, 0xf6, 0x81, 0x77, 0xfb, 0x18, 0xbc, 0xbb,
	0x1e, 0xbd, 0xe1, 0x33, 0x0c, 0xe8, 0xad, 0x88, 0x81, 0xba, 0xe9, 0xd1, 0x47, 0xe7, 0x77, 0xf8,
	0x14, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xbf, 0xff, 0x00, 0x4e, 0x02, 0x00, 0x00,
}
