apiVersion: agents.aljabr.io/v1alpha1
kind: TaskExecutor
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: filedrop-taskexecutor
spec:
  type: FileDrop
  container:
    image: koalja-tasks:latest
    command:
    - /apps/tasks
    - filedrop
    - --target
    - "{{(index .outputs ((index .task.Outputs 0).Name)).path}}"
    - --volume-name
    - "{{(index .outputs ((index .task.Outputs 0).Name)).volumeName}}"
    - --volume-claim-name
    - "{{(index .outputs ((index .task.Outputs 0).Name)).volumeClaimName}}"
    - --volume-path
    - "{{(index .outputs ((index .task.Outputs 0).Name)).volumePath}}"
    - --sub-path
    - "{{(index .outputs ((index .task.Outputs 0).Name)).subPath}}"
    - --mount-path
    - "{{(index .outputs ((index .task.Outputs 0).Name)).mountPath}}"
    - --node-name
    - "{{(index .outputs ((index .task.Outputs 0).Name)).nodeName}}"
    - --output-name
    - "{{(index .task.Outputs 0).Name}}"
  routes:
  - name: "upload"
    port: 8080
    prefixRewrite: "/upload"
