apiVersion: agents.aljabr.io/v1alpha1
kind: Link
metadata:
  name: stub-link-agent
  namespace: default
spec:
  container:
    image: koalja-agents:latest
    command:
    - /apps/agents
    - link
    - --queue=stub
