apiVersion: agents.aljabr.io/v1alpha1
kind: Pipeline
metadata:
  name: default-pipeline-agent
  namespace: default
spec:
  container:
    image: koalja-agents:latest
    command:
    - /apps/agents
    - pipeline
